# Generated by Django 5.2.8 on 2025-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('resumen', models.TextField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('cover_url', models.URLField(blank=True, help_text='URL de imagen/pantallazo principal (opcional)')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='proyectos', to='sitio.tag')),
            ],
            options={
                'ordering': ['orden', '-creado'],
            },
        ),
    ]
